/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ravialledulla' at '11/4/15 10:57 PM' with Gradle 2.6
 *
 * @author ravialledulla, @date 11/4/15 10:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
